// REMPLACEZ CES PLACEHOLDERS PAR VOS VRAIES CLÉS SUPABASE
const SUPABASE_URL = 'VOTRE_URL_SUPABASE'; 
const SUPABASE_ANON_KEY = 'VOTRE_CLE_ANON_PUBLIQUE'; 

const supabase = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
